### ISSUE TITLE
command line parameters not applied for the twine fallback

### ISSUE THREAD

**Issue by sebhmg** [jedie/poetry-publish#5]
Thanks for the convenient package.
I was trying to use it to publish onto TestPypi with `poetry run publish -r testpypi`
fallbacks is applied, and _twine_ run without the repository option, thus targeting the default Pypi repository.

I have patched locally the code for the _twine_ fallback as follow:
```python
        print('\nPoetry publish error -> fallback and use twine')
        args = ['poetry', 'run', 'twine', 'upload', 'dist/*.*'] + sys.argv[1:]
        verbose_check_call(*args)
```

Cheers

**Comment by sebhmg** [comment]
for the record, this how I have configured the testpypi repo:
```sh
poetry config repositories.testpypi https://test.pypi.org/
```
according to the _poetry_ documentation for [adding a repository](https://python-poetry.org/docs/repositories/#adding-a-repository)

**Comment by jedie** [comment]
Ah! Now i see this issues for #7

Okay: This is generally a good idea. But the realization with passing args to twine is a bad idea.

We should add real argument parsing and add something like: "--testpypi" to switch the pypi server.

**Comment by jedie** [comment]
fixed in https://github.com/jedie/poetry-publish/pull/20
